### ISSUE TITLE
Plugin resets the the checkbox line indentation

### ISSUE THREAD

**Issue by piRGoif** [Nomekuma/auto-strikethrough-task-obsidian-pluggin#1]
Hello,

The plugin resets indentation of the checkbox :(

For example : 

````
- list title
  - [ ] my item 1
  - [ ] my item 2
  - [ ] my item 3
`````

Checking will result in : 

```
- list title
  - [ ] my item 1
- [X] ~~my item 2~~
  - [ ] my item 3
````````

Running version 0.0.1 on Obsidian 1.6.7 on Ubuntu 22.04

**Comment by Nomekuma** [comment]
Hello,

Thank you for bringing this to my attention! I will look into the issue and investigate the behavior with checkbox indentation.

**Comment by piRGoif** [comment]
Many thanks ! 
I see this fix in the 0.0.2 release, so nice it was done so quickly \o/
Obsidian doesn't show me this version though, do you know when it will be available ?

**Comment by Nomekuma** [comment]
Thanks! Glad you’re excited about the 0.0.2 fix. It should be available in Obsidian within a day or two, depending on their rollout.

**Comment by piRGoif** [comment]
Perfect; thanks !

**Comment by Nomekuma** [comment]
The update is in the Obsidian store! 🥳

**Comment by piRGoif** [comment]
Thanks !
Just installed the update, no more issue on my side !
Thanks again !
